name: Build Release Executable
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions:
    contents: write
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pygame pyinstaller uv
            - name: Build executable with PyInstaller
              run: |
                  pyinstaller Monopoly.spec
              shell: bash
            - name: Rename executable for identification
              run: |
                VERSION=$(uv version)
                mv dist/Monopoly.exe dist/Monopoly-${VERSION}.exe
              shell: bash
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: monopoly-executable
                  path: dist/Monopoly*
    release:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
            - name: List downloaded artifacts (debug)
              run: |
                  echo "Estrutura dos artifacts baixados:"
                  find artifacts -type f -name "*" | head -20
                  echo "Conteúdo detalhado:"
                  ls -la artifacts/*/
            - name: Prepare release files
              run: |
                  mkdir -p release-files
                  find artifacts -name "Monopoly*" -type f -exec cp {} release-files/ \;
                  echo "Arquivos preparados para release:"
                  ls -la release-files/
            - name: Delete existing release
              run: |
                  gh release delete latest --yes || true
                  git tag -d latest || true
                  git push origin :refs/tags/latest || true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  name: "Latest Release"
                  tag_name: "latest"
                  files: release-files/*
                  body: |
                      Executáveis atualizados automaticamente a partir do commit: ${{ github.sha }}
                      
                      **Arquivo executável:**
                      - `Monopoly-${VERSION}.exe`
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}