name: Build Test Executable
on:
    push:
        branches: [release]
    pull_request:
        branches: [release]
permissions:
    contents: write
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pygame pyinstaller pytest
            - name: Build executable with PyInstaller
              run: |
                  pyinstaller --onefile --name Monopoly app/main.py
            - name: Rename executable for identification
              run: |
                  if [ "${{ runner.os }}" = "Linux" ]; then
                    mv dist/Monopoly dist/Monopoly-linux
                  elif [ "${{ runner.os }}" = "macOS" ]; then
                    mv dist/Monopoly dist/Monopoly-macos
                  elif [ "${{ runner.os }}" = "Windows" ]; then
                    mv dist/Monopoly.exe dist/Monopoly-windows.exe
                  fi
              shell: bash
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: monopoly-executable-${{ matrix.os }}
                  path: dist/Monopoly*

    upload:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/release' && github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
            - name: List downloaded artifacts (debug)
              run: |
                  echo "Estrutura dos artifacts baixados:"
                  find artifacts -type f -name "*" | head -20
                  echo "Conteúdo detalhado:"
                  ls -la artifacts/*/
            - name: Install AWS CLI
              run: |
                  python -m pip install --upgrade pip
                  pip install awscli
            - name: Upload to DigitalOcean Spaces
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
              run: |
                  aws --version
                  aws s3 sync artifacts/ s3://${{ secrets.DO_SPACES_BUCKET }}/ --acl public-read --endpoint-url ${{ secrets.DO_SPACES_ENDPOINT }}

